FROM php:8.1-fpm-alpine

RUN docker-php-ext-install pdo pdo_mysql

ENV COMPOSER_ALLOW_SPUERUSER=1

COPY --from=composer:2.4 /usr/bin/composer /usr/bin/composer

COPY ./app/composer.* ./

RUN composer update --prefer-dist --no-dev --no-interaction --no-scripts 

COPY ./app .

RUN composer dump-autoload --optimize 