<?php

const ROUTE_METHOD_GET = 'GET';
const ROUTE_METHOD_POST = 'POST';

const SESSION_USER_LOGGED_IN = 'USER_LOGGED_IN';
const SESSION_USER_EMAIL='USER_EMAIL';
const SESSION_USER_ROLE='USER_ROLE';
const SESSION_FIRST_NAME='USER_FIRST_NAME';
const SESSION_LAST_NAME='USER_LAST_NAME';
